const row = [
  null,
  null,
  null,
  null,
  { io: IO1, index: 8 },
  { io: IO1, index: 128 },
  { io: IO2, index: 7 },
  { io: IO2, index: 6 },
  { io: IO2, index: 5 },
  { io: IO2, index: 4 },
  { io: IO2, index: 3 },
  { io: IO2, index: 2 },
  { io: IO2, index: 1 },
  { io: IO2, index: 82 },
  { io: IO2, index: 81 },
  { io: IO2, index: 96 },
  { io: IO2, index: 95 },
  { io: IO2, index: 94 },
  { io: IO2, index: 93 },
  { io: IO2, index: 92 },
  { io: IO4, index: 41 },
  { io: IO4, index: 40 },
  { io: IO4, index: 39 },
  { io: IO4, index: 38 },
  { io: IO4, index: 37 },
  { io: IO4, index: 36 },
  { io: IO4, index: 35 },
  { io: IO4, index: 34 },
  { io: IO4, index: 128 },
  { io: IO5, index: 3 },
  { io: IO5, index: 4 },
  { io: IO5, index: 5 },
  { io: IO5, index: 6 },
  { io: IO5, index: 7 },
  { io: IO5, index: 8 },
  { io: IO6, index: 56 },
  { io: IO6, index: 55 },
  { io: IO6, index: 54 },
  { io: IO6, index: 60 },
  { io: IO6, index: 61 },
  { io: IO6, index: 62 },
  { io: IO6, index: 63 },
  { io: IO6, index: 64 },
  { io: IO6, index: 113 },
  null,
  null,
  null,
  { io: IO6, index: 116 }
];

const { IO1, IO2, IO3, IO4, IO5, IO6 } = require('./index');

module.exports = row;
