const { IO1, IO2, IO3, IO4, IO5, IO6 } = require('../constants');
const row = [
  null,
  null,
  null,
  null,
  null,
  { io: IO1, index: 27 },
  null,
  null,
  { io: IO1, index: 25 },
  null,
  { io: IO1, index: 37 },
  { io: IO1, index: 36 },
  null,
  null,
  { io: IO3, index: 49 },
  { io: IO3, index: 50 },
  null,
  { io: IO3, index: 51 },
  null,
  null,
  { io: IO3, index: 59 },
  null,
  null,
  { io: IO3, index: 55 },
  null,
  { io: IO3, index: 56 },
  null,
  { io: IO3, index: 65 },
  null,
  { io: IO5, index: 94 },
  { io: IO5, index: 93 },
  null,
  null,
  { io: IO5, index: 89 },
  null,
  { io: IO5, index: 102 },
  null,
  null,
  null,
  { io: IO5, index: 98 },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null
];

module.exports = row;
