const { IO1, IO2, IO3, IO4, IO5, IO6 } = require('../constants');
const row = [
  null,
  null,
  null,
  null,
  null,
  null,
  { io: IO1, index: 43 },
  null,
  { io: IO1, index: 42 },
  { io: IO1, index: 41 },
  { io: IO1, index: 40 },
  { io: IO1, index: 39 },
  { io: IO1, index: 38 },
  { io: IO3, index: 33 },
  { io: IO3, index: 48 },
  { io: IO3, index: 47 },
  { io: IO3, index: 46 },
  { io: IO3, index: 45 },
  { io: IO3, index: 44 },
  null,
  { io: IO3, index: 73 },
  { io: IO3, index: 72 },
  { io: IO3, index: 71 },
  { io: IO3, index: 70 },
  { io: IO3, index: 69 },
  { io: IO3, index: 68 },
  { io: IO3, index: 67 },
  { io: IO3, index: 66 },
  { io: IO5, index: 81 },
  null,
  { io: IO5, index: 82 },
  { io: IO5, index: 83 },
  { io: IO5, index: 84 },
  null,
  { io: IO5, index: 85 },
  { io: IO5, index: 103 },
  { io: IO5, index: 100 },
  null,
  null,
  { io: IO5, index: 112 },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null
];

module.exports = row;
