const { IO1, IO2, IO3, IO4, IO5, IO6 } = require('../constants');
const row = [
  null,
  null,
  null,
  { io: IO1, index: 2 },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  { io: IO2, index: 49 },
  { io: IO2, index: 50 },
  null,
  { io: IO2, index: 51 },
  { io: IO2, index: 52 },
  null,
  { io: IO2, index: 53 },
  null,
  null,
  { io: IO4, index: 76 },
  null,
  { io: IO4, index: 79 },
  { io: IO4, index: 86 },
  null,
  { io: IO4, index: 85 },
  null,
  null,
  { io: IO4, index: 94 },
  null,
  { io: IO4, index: 84 },
  { io: IO4, index: 82 },
  null,
  { io: IO6, index: 92 },
  { io: IO6, index: 93 },
  { io: IO6, index: 94 },
  null,
  { io: IO6, index: 95 },
  null,
  { io: IO6, index: 96 },
  null,
  { io: IO6, index: 99 },
  null,
  null,
  null,
  null
];

module.exports = row;
