const { IO1, IO2, IO3, IO4, IO5, IO6 } = require('../constants');
const row = [
  null,
  null,
  null,
  null,
  { io: IO1, index: 3 },
  null,
  null,
  null,
  { io: IO2, index: 39 },
  { io: IO2, index: 38 },
  null,
  { io: IO2, index: 36 },
  { io: IO2, index: 35 },
  { io: IO2, index: 64 },
  { io: IO2, index: 63 },
  null,
  { io: IO2, index: 62 },
  { io: IO2, index: 54 },
  { io: IO2, index: 55 },
  { io: IO2, index: 56 },
  { io: IO4, index: 74 },
  { io: IO4, index: 75 },
  null,
  { io: IO4, index: 77 },
  { io: IO4, index: 78 },
  null,
  { io: IO4, index: 80 },
  null,
  { io: IO4, index: 92 },
  { io: IO4, index: 93 },
  { io: IO4, index: 102 },
  { io: IO4, index: 103 },
  { io: IO4, index: 104 },
  null,
  null,
  { io: IO6, index: 89 },
  null,
  null,
  { io: IO6, index: 90 },
  null,
  { io: IO6, index: 91 },
  null,
  null,
  null,
  null,
  { io: IO6, index: 97 },
  null,
  null
];

module.exports = row;
